name: CI

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Rodar testes
        run: |
          cd src
          pytest --maxfail=3 --disable-warnings -v tests
      - name: Rodar linter (flake8)
        run: |
          pip install flake8
          flake8 src/
      - name: Rodar formatter (black)
        run: |
          pip install black
          black --check src/
      - name: Validar cobertura mínima
        run: |
          pip install pytest-cov
          pytest --cov=src/services --cov-report=term-missing
